server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/notification_db}
    username: ${DB_USER:tickethub}
    password: ${DB_PASSWORD:tickethub}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.pavankumar.tickethub.common.events

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
